### ISSUE TITLE
download file not found

### ISSUE THREAD

**Issue by slfhstr** [binuengoor/OpenSpeech#1]
The script to download the output file after completion is not working.
```
FileNotFoundError

FileNotFoundError: [Errno 2] No such file or directory: 'output.mp3'
```

Traceback :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app.py", line 102, in download_file
    with open('output.mp3', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output.mp3'
```

**Comment by TylonHH** [comment]
you solved this?
